shopflow_analytics:
  outputs:
    dev:
      account: '*****************'
      database: analytics_db
      password: '*****************'
      role: TRANSFORM
      schema: landing
      threads: 1
      type: snowflake
      user: dbt_user
      warehouse: COMPUTE_WH

    prod:
      account: '*****************'
      database: analytics_db
      password: '*****************'
      role: TRANSFORM
      schema: landing
      threads: 1
      type: snowflake
      user: dbt_user
      warehouse: COMPUTE_WH
  target: dev
